### ISSUE TITLE
2022.11.12 기능 / 역할분담

### ISSUE THREAD

**Issue by evelo0702** [BOOKPROJECT00/USED-BOOK#6]
기능 
1. 검색어 입력하고 엔터 - > 리스트화면 넘어가기 
2. 검색어 추천리스트 클릭시 상세화면 넘어가기
3. 베스트셀러 책 클릭시 상세화면  
4. 검색 리스트 페이지네이션 
5. 관심 도서 찜하기 / 취소
6. 중고 상세페이지 찜하기 / 취소
7. 로그인정보 vuex 
8. 서재 데이터 불러오기 
9. 상세보기 api호출

=====================================
1. db 설계 보완
중고책등록할때 위도,경도 
채팅 db설계 
2. 주소등록 api 카카오로 변경 

=====================================
*************************************************************
채팅 api 완성
카카오맵 api 완성 

=======================================

**Comment by ssssssjay** [comment]
`api`나 데이터베이스 관련 문항 제외하고 제 역할은 다른 이슈로 분리했습니다😀
